package eu.kotkas.villak.core.model.enums;

/**
 * @author Kristen Kotkas
 */
public enum Action {

  QUESTION_CLOSE,
  QUESTION_OPEN,
  QUESTION_ANSWERED,
  QUESTION_SILVER,
  TEAM_SCORE,
  CATEGORY_SHOW,
  CATEGORY_HIDE,
  ROUND_ACTIVE,
  PRESS_BUTTON,
  RESET_BUTTON,
  SHOW_QUICKEST,
  CLOSE_BUTTON,
  TOGGLE_WINNER,
  GET_CURRENT,
  SET_ADMIN_DEVICE_ID,
  SET_CLIENT_DEVICE_ID,
  SET_TEAM_DEVICE_ID,
  SYNC_BUTTON,

}
